### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Rudloff** [sfilmak/MakiLite#6]
Hello,

I'm getting this error when trying to build 847ebe9b5651b7342a675c91569dc5335a970756:
```
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/home/pierre/www/MakiLite/app/src/main/java/com/sunshine/makilite/notifications/MakiReceiver.java:19: error: class, interface, or enum expected
package com.sunshine.makilite.activities.MakiApplication;
^
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by coderwjq** [comment]
散了吧，散了吧，这个项目运行不了

**Comment by sfilmak** [comment]
Hello! 

This is a source code of very old version of Maki, so yeah, it is not actual now. I'm planning to publish the source code of Maki 2.x during this year in this repository after I will make a project to look better inside. 

Stay tuned and don't miss any updates, please. Thank you!
